// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "github.com/mavrk-mose/pay/internal/payment/models"
	mock "github.com/stretchr/testify/mock"
)

// ExecutorService is an autogenerated mock type for the ExecutorService type
type ExecutorService struct {
	mock.Mock
}

// ExecutePayment provides a mock function with given fields: order
func (_m *ExecutorService) ExecutePayment(order models.PaymentIntent) (interface{}, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for ExecutePayment")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(models.PaymentIntent) (interface{}, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(models.PaymentIntent) interface{}); ok {
		r0 = rf(order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(models.PaymentIntent) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordPaymentOrder provides a mock function with given fields: order
func (_m *ExecutorService) RecordPaymentOrder(order models.PaymentIntent) error {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for RecordPaymentOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.PaymentIntent) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentExecutorService creates a new instance of ExecutorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentExecutorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutorService {
	mock := &ExecutorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
