// Code generated by mockery v2.53.3. DO NOT EDIT.

package repository

import (
	context "context"
	"reflect"
	"testing"

	goth "github.com/markbates/goth"
	models "github.com/mavrk-mose/pay/internal/user/models"
	mock "github.com/stretchr/testify/mock"
	mocks "github.com/mavrk-mose/pay/internal/user/repository/mocks"
)


func TestNewUserRepository(t *testing.T) {
	type args struct {
		t interface {
			mock.TestingT
			Cleanup(func())
		}
	}
	tests := []struct {
		name string
		args args
		want *UserRepository
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := mocks.NewUserRepository(tt.args.t); !reflect.DeepEqual(got, tt.want) {
				t.Errorf("NewUserRepository() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestUserRepository_AssignRole(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		userID string
		role   string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			if err := _m.AssignRole(tt.args.ctx, tt.args.userID, tt.args.role); (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.AssignRole() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestUserRepository_BanUser(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		userID string
		reason string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			if err := _m.BanUser(tt.args.ctx, tt.args.userID, tt.args.reason); (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.BanUser() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestUserRepository_CreateOrUpdateUser(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx  context.Context
		user goth.User
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    *models.User
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			got, err := _m.CreateOrUpdateUser(tt.args.ctx, tt.args.user)
			if (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.CreateOrUpdateUser() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("UserRepository.CreateOrUpdateUser() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestUserRepository_GetUserByID(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		userID string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    *models.User
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			got, err := _m.GetUserByID(tt.args.ctx, tt.args.userID)
			if (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.GetUserByID() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("UserRepository.GetUserByID() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestUserRepository_ListUsers(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		filter models.UserFilter
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		want    []models.User
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			got, err := _m.ListUsers(tt.args.ctx, tt.args.filter)
			if (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.ListUsers() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("UserRepository.ListUsers() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestUserRepository_RevokeRole(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		userID string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			if err := _m.RevokeRole(tt.args.ctx, tt.args.userID); (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.RevokeRole() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestUserRepository_UnbanUser(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx    context.Context
		userID string
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			if err := _m.UnbanUser(tt.args.ctx, tt.args.userID); (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.UnbanUser() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestUserRepository_UpdateUser(t *testing.T) {
	type fields struct {
		Mock mock.Mock
	}
	type args struct {
		ctx     context.Context
		userID  string
		updates models.UserUpdateRequest
	}
	tests := []struct {
		name    string
		fields  fields
		args    args
		wantErr bool
	}{
		// TODO: Add test cases.
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_m := &mocks.UserRepository{
				Mock: tt.fields.Mock,
			}
			if err := _m.UpdateUser(tt.args.ctx, tt.args.userID, tt.args.updates); (err != nil) != tt.wantErr {
				t.Errorf("UserRepository.UpdateUser() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}
